# Generated by Django 3.0 on 2020-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(default='', max_length=50)),
                ('cource_fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cource_short_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('cource_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('p_photo', models.ImageField(default='', upload_to='cource')),
            ],
        ),
    ]
