# Generated by Django 3.0 on 2020-03-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courcemodel',
            old_name='p_photo',
            new_name='cource_photo',
        ),
    ]
