# Generated by Django 3.0 on 2020-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0003_auto_20200313_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='courcemodel',
            name='slug',
            field=models.SlugField(default='ccs'),
            preserve_default=False,
        ),
    ]
