# Generated by Django 3.0 on 2020-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0004_courcemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('College', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('JGCCA', 'JGCCA'), ('SLICA', 'SLICA')], default='NONE', max_length=50, null=True)),
                ('Semester', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], default='NONE', max_length=50, null=True)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Cource', models.CharField(choices=[('NONE', 'NONE'), ('Website Development', 'Website Development'), ('Mobile Development', 'Mobile Development'), ('Vacation Cources', 'Vacation Cources'), ('Short Cources', 'Short Cources'), ('Live Project Training', 'Live Project Training'), ('BCA Coaching', 'BCA Coaching')], default='OTHER', max_length=50)),
            ],
        ),
    ]
