# Generated by Django 3.0 on 2020-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0005_enquirymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirymodel',
            name='College',
            field=models.CharField(blank=True, default='NONE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='Cource',
            field=models.CharField(default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='enquirymodel',
            name='Semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
